export const authConstants ={
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FALIURE: 'LOGIN_FALIURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    SIGN_UP_REQUEST: 'SIGNUP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
}

export const bookConstants ={
    INSERT_BOOK_REQUEST: 'INSERT_BOOK_REQUEST',
    INSERT_BOOK_FALIURE: 'INSERT_BOOK_FALIURE',
    INSERT_BOOK_SUCCESS: 'INSERT_BOOK_SUCCESS',
    RETRIVE_BOOKS_REQUEST: 'RETRIVE_BOOKS_REQUEST',
    RETRIVE_BOOKS_SUCCESS: 'RETRIVE_BOOKS_SUCCESS',
    RETRIVE_BOOKS_FAILURE: 'RETRIVE_BOOKS_FAILURE',
    DELETE_BOOK_REQUEST: 'DELETE_BOOK_REQUEST',
    DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
    DELETE_BOOK_FAILED: 'DELETE_BOOK_FAILED',
    UPDATE_BOOK_REQUEST: 'UPDATE_BOOK_REQUEST',
    UPDATE_BOOK_SUCCESS: 'UPDATE_BOOK_SUCCESS',
    UPDATE_BOOK_FAILED: 'UPDATE_BOOK_FAILED',
}